name: "Export secrets"

on:
  push:
    branches:
      - chore/secrets

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: gpg import
        run: |
          gpg --import public.asc
          gpg -k
      - name: create .env file
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          FINGERPRINT: ${{ secrets.FINGERPRINT }}
        run: env > .env

      - name: encrypt .env
        run: gpg -a --encrypt --recipient koen.de.laat@philips.com --trust-model always .env

      - name: print .env.asc
        run: cat .env.asc